[package]
name = "protify_server"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0" # Colors for terminals
mysql = "24.0.0" # Database connection
serde_json = "=1.0.114" # Json Encoder/Decoder
